server:
  port: 9090
spring:
  datasource:
    # jdbc:mysql::/localhost/{dbName}
    # jdbc:postgresql://localhost:5432/{dbName}
    url: 
    # com.mysql.jdbc.Driver
    driverClassName: 
    username: 
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update